'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports DevExpress.Xpo
Imports System.Runtime.InteropServices

Namespace XpoTutorial1.DataModel

    Public Module ConnectionHelper

        Public Const ConnectionString As String = "XpoProvider=MSSqlServer;data source=(local);integrated security=SSPI;initial catalog=XpoTutorial1"

        Public Sub Connect(ByVal autoCreateOption As DB.AutoCreateOption)
            XpoDefault.DataLayer = XpoDefault.GetDataLayer(ConnectionString, autoCreateOption)
            XpoDefault.Session = Nothing
        End Sub

        Public Function GetConnectionProvider(ByVal autoCreateOption As DB.AutoCreateOption) As DB.IDataStore
            Return XpoDefault.GetConnectionProvider(ConnectionString, autoCreateOption)
        End Function

        Public Function GetConnectionProvider(ByVal autoCreateOption As DB.AutoCreateOption, <Out> ByRef objectsToDisposeOnDisconnect As IDisposable()) As DB.IDataStore
            Return XpoDefault.GetConnectionProvider(ConnectionString, autoCreateOption, objectsToDisposeOnDisconnect)
        End Function

        Public Function GetDataLayer(ByVal autoCreateOption As DB.AutoCreateOption) As IDataLayer
            Return XpoDefault.GetDataLayer(ConnectionString, autoCreateOption)
        End Function
    End Module
End Namespace
