'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports DevExpress.Xpo
Imports DevExpress.Data.Filtering

Namespace XpoTutorial1.DataModel

    Public Partial Class Customer
        Inherits DevExpress.Xpo.XPObject

        Private fName As String

        Public Property Name As String
            Get
                Return Me.fName
            End Get

            Set(ByVal value As String)
                Call SetPropertyValue(Of String)("Name", Me.fName, value)
            End Set
        End Property

        Private fAge As UShort

        Public Property Age As UShort
            Get
                Return Me.fAge
            End Get

            Set(ByVal value As UShort)
                Call SetPropertyValue(Of UShort)("Age", Me.fAge, value)
            End Set
        End Property
    End Class
End Namespace
