'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports DevExpress.Xpo
Imports DevExpress.Data.Filtering
Namespace XpoTutorial1.DataModel
	Public Module ConnectionHelper
		Public Const ConnectionString As String = "XpoProvider=MSSqlServer;data source=(local);integrated security=SSPI;initial catalog=XpoTutorial1"
		Public Sub Connect(ByVal autoCreateOption As DevExpress.Xpo.DB.AutoCreateOption)
			XpoDefault.DataLayer = XpoDefault.GetDataLayer(ConnectionString, autoCreateOption)
			XpoDefault.Session = Nothing
		End Sub
		Public Function GetConnectionProvider(ByVal autoCreateOption As DevExpress.Xpo.DB.AutoCreateOption) As DevExpress.Xpo.DB.IDataStore
			Return XpoDefault.GetConnectionProvider(ConnectionString, autoCreateOption)
		End Function
		Public Function GetConnectionProvider(ByVal autoCreateOption As DevExpress.Xpo.DB.AutoCreateOption, <System.Runtime.InteropServices.Out()> ByRef objectsToDisposeOnDisconnect() As IDisposable) As DevExpress.Xpo.DB.IDataStore
			Return XpoDefault.GetConnectionProvider(ConnectionString, autoCreateOption, objectsToDisposeOnDisconnect)
		End Function
		Public Function GetDataLayer(ByVal autoCreateOption As DevExpress.Xpo.DB.AutoCreateOption) As IDataLayer
			Return XpoDefault.GetDataLayer(ConnectionString, autoCreateOption)
		End Function
	End Module

End Namespace
